#!/usr/bin/env node
var crush       = require('./index')
var JSONStream  = require('JSONStream')
var results     = crush(process.argv[2])


results.on('error', function(err) {
  console.log('error', err)
  process.exit(1)
})

results
  .pipe(JSONStream.stringify())
  .pipe(process.stdout)
