#!/usr/bin/env node
var crush   = require('./index'),
    _  = require('underscore')
    
var args  = require('optimist').argv

function asArray() {
  return _.unique(_.flatten(arguments))
}

var results = crush(args._, {
  transform: asArray(args.transform, args.t),
  extensions: asArray(args.extension)
})

results.asPromise()
  .then(function(result) {
    console.log(JSON.stringify(result))
  })
  .fail(function(err) {
    console.log(err.message || err)
    process.exit(1)
  })
  .end()
